### ISSUE TITLE
Keeping all service timing/logs for slow requests?

### ISSUE THREAD

**Issue by rcoup** [AppEnlight/appenlight-client-python#45]
Example -- a badly behaved Django request ends up making 200 SQL queries and takes 2 seconds (so triggers slow-request handling):

* you can see that 200 queries happened in the breakdown bar on the left
* but each query is individually quick (eg. taking 10ms)
* so there's no breakdown on what it's actually doing in your slow request
* so it's harder than it needs to be to diagnose

I guess the approach is to accumulate all log/timing info _before_ deciding whether to report the slow request? 

Setting `appenlight.timing.{library} = 0` for everything appears to achieve that without triggering slow-reporting for individual service calls that exceed the timing threshold.  (well, 0.001 -- 0 doesn't actually work in practice)

For logging, `logging_on_error` [doesn't appear to be used at all](https://github.com/AppEnlight/appenlight-client-python/search?utf8=%E2%9C%93&q=logging_on_error)? -- either the logging is always on or off.

Am I missing something?

**Comment by ergo** [comment]
Hey @rcoup 

logging_on_error means that if you have logging on - it will only send logs when you have a 500 or a slow report - otherwise the logs are ignored.

Yes, I'll think about some better solution for that, but the tricky part is sometimes you can have thousands of queries that you want - and storing them per request will inflate the memory - so I'm trying to have middle ground here where unexpected situations will not make client eat more memory than necessary.

I'm open to ideas on how to improve here - I could add some additional environ var like "force timing" or something along the lines that could give you control on how to handle this situation.

**Comment by ergo** [comment]
No feedback since 2017. Closing.
